from country_bounding_boxes import country_subunits_by_iso_code

Data = [
    {
        "type": "cities",
        "data": {
            "Sydney": {"latitude": -33.8688, "longitude": 151.2093},
            "Mumbai": {"latitude": 19.0760, "longitude": 72.8777},
            "New York": {"latitude": 40.7128, "longitude": -74.0060},
            "Washington": {"latitude": 38.9072, "longitude": -77.0369},
            "Mexico City": {"latitude": 19.4326, "longitude": -99.1332},
            "Rio de Janeiro": {"latitude": -22.9068, "longitude": -43.1729},
            "Cairo": {"latitude": 30.0444, "longitude": 31.2357},
            "Kinshasa": {"latitude": -4.4419, "longitude": 15.2663},
            "New Delhi": {"latitude": 28.6139, "longitude": 77.2090},
            "Tokyo": {"latitude": 35.6895, "longitude": 139.6917},
            "Beijing": {"latitude": 39.9042, "longitude": 116.4074},
            "Moscow": {"latitude": 55.7558, "longitude": 37.6173},
        },
    },
    {
        "type": "rivieren",
        "data": {
            "Amazon River": {
                "coordinates": [
                    (-73.465162, -4.453738),
                    (-60.0, -3.0),
                    (-55.0, -2.0),
                    (-49.854727, 1.165481),
                ]
            },
            "Mississippi": {
                "coordinates": [
                    (-89.2533, 29.1511),
                    (-91.1447, 30.4575),
                    (-90.8789, 32.3486),
                    (-90.0500, 35.1497),
                    (-89.1675, 37.0136),
                    (-90.1961, 38.6311),
                    (-90.6639, 42.5017),
                    (-91.2525, 43.8136),
                    (-93.2650, 44.9800),
                    (-95.2075, 47.2397),
                ]
            },
            "Gele Rivier": {
                "coordinates": [(101.5, 41.7), (106.0, 36.5), (111.0, 34.5), (119.5, 32.0)]
            },
            "Ganges": {"coordinates": [(79.1, 30.9), (83.0, 25.3), (88.3, 22.5)]},
            "Blauwe Rivier": {
                "coordinates": [
                    (91.2, 33.7),
                    (103.8, 29.6),
                    (112.9, 30.7),
                    (121.8, 31.4),
                ]
            },
            "Indus": {"coordinates": [(76.8, 35.7), (72.8, 32.1), (68.9, 24.8)]},
            "Mekong": {
                "coordinates": [
                    (94.6, 33.7),
                    (100.6, 21.7),
                    (105.8, 17.0),
                    (106.7, 10.8),
                ]
            },
            "Nijl": {"coordinates": [(31.2, 30.0), (32.6, 15.6), (30.5, 3.4)]},
            "Kongo (Congo)": {
                "coordinates": [(29.2, -2.5), (23.6, -4.3), (15.3, -4.8), (12.4, -6.1)]
            },
        },
    },
    {
        "type": "oceanen",
        "data": {
            "Atlantische Oceaan": {"bbox": [-80, -60, 20, 70]},
            "Indische Oceaan": {"bbox": [20, -60, 120, 30]},
            "Grote of Stille Oceaan": {"bbox": [120, -60, -80, 60]},
            "Noordelijke IJszee": {"bbox": [-180, 70, 180, 90]},
            "Middellandse Zee": {"bbox": [-6, 30, 36, 46]},
            "Zwarte Zee": {"bbox": [27, 41, 42, 47]},
            "Kaspische Zee": {"bbox": [47, 36, 55, 47]},
            "Rode Zee": {"bbox": [32, 12, 44, 30]},
            "Caribische Zee": {"bbox": [-90, 10, -60, 25]},
            "Noordzee": {"bbox": [-5, 51, 9, 61]},
            "Perzische Golf": {"bbox": [47, 24, 57, 31]},
            "Golf van Mexico": {"bbox": [-98, 18, -81, 31]},
            "Panamakanaal": {"bbox": [-80, 8, -79, 9]},
            "Suezkanaal": {"bbox": [32, 29, 33, 31]},
        },
    },
    {
        "type": "bergen",
        "data": {
            "Atlasgebergte": {"bbox": [-10, 30, 5, 35]},
            "Himalaya": {"bbox": [70, 25, 100, 35]},
            "Andes": {"bbox": [-80, -55, -60, 10]},
            "Rocky Mountains": {"bbox": [-125, 30, -105, 60]},
            "Oeral": {"bbox": [58, 45, 62, 68]},
            "Alpen": {"bbox": [5, 44, 15, 48]},
        },
    },
    {
        "type": "landen",
        "data": {
            c[0]: {"bbox": country_subunits_by_iso_code(c[1])}
            for c in [
                ("China", "CN"),
                ("Russia", "RU"),
                ("US", "US"),
                ("Brazil", "BR"),
                ("Egypt", "EG"),
                ("Algeria", "DZ"),
                ("Sudan", "SD"),
                ("Morocco", "MA"),
                ("Tunisia", "TN"),
                ("Libya", "LY"),
                ("Turkey", "TR"),
                ("Iran", "IR"),
                ("Iraq", "IQ"),
                ("Saudi Arabia", "SA"),
                ("Yemen", "YE"),
                ("Syria", "SY"),
                ("Jordan", "JO"),
                ("United Arab Emirates", "AE"),
                ("Israel", "IL"),
                ("Lebanon", "LB"),
                ("Oman", "OM"),
                ("Palestine", "PS"),
                ("Kuwait", "KW"),
                ("Qatar", "QA"),
                ("Bahrain", "BH"),
                ("Cyprus", "CY"),
                ("Mexico", "MX"),
                ("Congo (Democratic Republic)", "CD"),
                ("India", "IN"),
                ("Pakistan", "PK"),
                ("Bangladesh", "BD"),
                ("Nepal", "NP"),
                ("Sri Lanka", "LK"),
                ("Bhutan", "BT"),
                ("Maldives", "MV"),
                ("Argentina", "AR"),
                ("Kazakhstan", "KZ"),
                ("Indonesia", "ID"),
                ("Philippines", "PH"),
                ("Vietnam", "VN"),
                ("Thailand", "TH"),
                ("Myanmar", "MM"),
                ("Malaysia", "MY"),
                ("Cambodia", "KH"),
                ("Laos", "LA"),
                ("Singapore", "SG"),
                ("Timor-Leste", "TL"),
                ("Brunei", "BN"),
                ("Nigeria", "NG"),
                ("South Africa", "ZA"),
                ("Australia", "AU"),
                ("Canada", "CA"),
                ("Colombia", "CO"),
                ("Peru", "PE"),
                ("Venezuela", "VE"),
                ("Chile", "CL"),
                ("Ecuador", "EC"),
                ("Guatemala", "GT"),
                ("Bolivia", "BO"),
                ("Haiti", "HT"),
                ("Cuba", "CU"),
                ("Dominican Republic", "DO"),
                ("Honduras", "HN"),
                ("Paraguay", "PY"),
                ("El Salvador", "SV"),
                ("Nicaragua", "NI"),
                ("Costa Rica", "CR"),
                ("Panama", "PA"),
                ("Uruguay", "UY"),
                ("Jamaica", "JM"),
                ("Trinidad and Tobago", "TT"),
                ("Guyana", "GY"),
                ("Suriname", "SR"),
                ("Belize", "BZ"),
                ("Bahamas", "BS"),
                ("Barbados", "BB"),
                ("Saint Lucia", "LC"),
                ("Grenada", "GD"),
                ("Saint Vincent and the Grenadines", "VC"),
                ("Antigua and Barbuda", "AG"),
                ("Dominica", "DM"),
                ("Saint Kitts and Nevis", "KN"),
                ("Germany", "DE"),
                ("United Kingdom", "GB"),
                ("France", "FR"),
                ("Italy", "IT"),
                ("Spain", "ES"),
                ("Ukraine", "UA"),
                ("Poland", "PL"),
                ("Romania", "RO"),
                ("Netherlands", "NL"),
                ("Belgium", "BE"),
                ("Greece", "GR"),
                ("Portugal", "PT"),
                ("Czechia", "CZ"),
                ("Hungary", "HU"),
                ("Sweden", "SE"),
                ("Austria", "AT"),
                ("Switzerland", "CH"),
                ("Bulgaria", "BG"),
                ("Denmark", "DK"),
                ("Finland", "FI"),
                ("Slovakia", "SK"),
                ("Norway", "NO"),
                ("Ireland", "IE"),
                ("Croatia", "HR"),
                ("Bosnia and Herzegovina", "BA"),
                ("Lithuania", "LT"),
                ("Slovenia", "SI"),
                ("Latvia", "LV"),
                ("Estonia", "EE"),
                ("North Macedonia", "MK"),
                ("Luxembourg", "LU"),
                ("Montenegro", "ME"),
                ("Malta", "MT"),
                ("Iceland", "IS"),
                ("Andorra", "AD"),
                ("Monaco", "MC"),
                ("Liechtenstein", "LI"),
                ("San Marino", "SM"),
                ("Vatican City", "VA"),
                ("Uzbekistan", "UZ"),
                ("Turkmenistan", "TM"),
                ("Tajikistan", "TJ"),
                ("Kyrgyzstan", "KG"),
                ("Ethiopia", "ET"),
                ("Tanzania", "TZ"),
                ("Kenya", "KE"),
                ("Uganda", "UG"),
                ("Angola", "AO"),
                ("Mozambique", "MZ"),
                ("Ghana", "GH"),
                ("Madagascar", "MG"),
                ("Cameroon", "CM"),
                ("Ivory Coast", "CI"),
                ("Niger", "NE"),
                ("Burkina Faso", "BF"),
                ("Mali", "ML"),
                ("Malawi", "MW"),
                ("Zambia", "ZM"),
                ("Senegal", "SN"),
                ("Chad", "TD"),
                ("Somalia", "SO"),
                ("Zimbabwe", "ZW"),
                ("Guinea", "GN"),
                ("Rwanda", "RW"),
                ("Benin", "BJ"),
                ("Burundi", "BI"),
                ("South Sudan", "SS"),
                ("Togo", "TG"),
                ("Sierra Leone", "SL"),
                ("Congo-Brazzaville", "CG"),
                ("Liberia", "LR"),
                ("Central African Republic", "CF"),
                ("Mauritania", "MR"),
                ("Eritrea", "ER"),
                ("Namibia", "NA"),
                ("Gambia", "GM"),
                ("Botswana", "BW"),
                ("Gabon", "GA"),
                ("Lesotho", "LS"),
                ("Guinea-Bissau", "GW"),
                ("Equatorial Guinea", "GQ"),
                ("Mauritius", "MU"),
                ("Eswatini", "SZ"),
                ("Djibouti", "DJ"),
                ("Comoros", "KM"),
                ("Cabo Verde", "CV"),
                ("Sao Tome and Principe", "ST"),
                ("Seychelles", "SC"),
            ]
            if country_subunits_by_iso_code(c[1]) is not None
        },
    },
    {
        "type": "countries_iso",
        "data": {
            c[0]: {"iso_code": c[1], "bbox": country_subunits_by_iso_code(c[1])}
            for c in [
                ("China", "CN"),
                ("Russia", "RU"),
                ("US", "US"),
                ("Brazil", "BR"),
                ("Egypt", "EG"),
                ("Algeria", "DZ"),
                ("Sudan", "SD"),
                ("Morocco", "MA"),
                ("Tunisia", "TN"),
                ("Libya", "LY"),
                ("Turkey", "TR"),
                ("Iran", "IR"),
                ("Iraq", "IQ"),
                ("Saudi Arabia", "SA"),
                ("Yemen", "YE"),
                ("Syria", "SY"),
                ("Jordan", "JO"),
                ("United Arab Emirates", "AE"),
                ("Israel", "IL"),
                ("Lebanon", "LB"),
                ("Oman", "OM"),
                ("Palestine", "PS"),
                ("Kuwait", "KW"),
                ("Qatar", "QA"),
                ("Bahrain", "BH"),
                ("Cyprus", "CY"),
                ("Mexico", "MX"),
                ("Congo (Democratic Republic)", "CD"),
                ("India", "IN"),
                ("Pakistan", "PK"),
                ("Bangladesh", "BD"),
                ("Nepal", "NP"),
                ("Sri Lanka", "LK"),
                ("Bhutan", "BT"),
                ("Maldives", "MV"),
                ("Argentina", "AR"),
                ("Kazakhstan", "KZ"),
                ("Indonesia", "ID"),
                ("Philippines", "PH"),
                ("Vietnam", "VN"),
                ("Thailand", "TH"),
                ("Myanmar", "MM"),
                ("Malaysia", "MY"),
                ("Cambodia", "KH"),
                ("Laos", "LA"),
                ("Singapore", "SG"),
                ("Timor-Leste", "TL"),
                ("Brunei", "BN"),
                ("Nigeria", "NG"),
                ("South Africa", "ZA"),
                ("Australia", "AU"),
                ("Canada", "CA"),
                ("Colombia", "CO"),
                ("Peru", "PE"),
                ("Venezuela", "VE"),
                ("Chile", "CL"),
                ("Ecuador", "EC"),
                ("Guatemala", "GT"),
                ("Bolivia", "BO"),
                ("Haiti", "HT"),
                ("Cuba", "CU"),
                ("Dominican Republic", "DO"),
                ("Honduras", "HN"),
                ("Paraguay", "PY"),
                ("El Salvador", "SV"),
                ("Nicaragua", "NI"),
                ("Costa Rica", "CR"),
                ("Panama", "PA"),
                ("Uruguay", "UY"),
                ("Jamaica", "JM"),
                ("Trinidad and Tobago", "TT"),
                ("Guyana", "GY"),
                ("Suriname", "SR"),
                ("Belize", "BZ"),
                ("Bahamas", "BS"),
                ("Barbados", "BB"),
                ("Saint Lucia", "LC"),
                ("Grenada", "GD"),
                ("Saint Vincent and the Grenadines", "VC"),
                ("Antigua and Barbuda", "AG"),
                ("Dominica", "DM"),
                ("Saint Kitts and Nevis", "KN"),
                ("Germany", "DE"),
                ("United Kingdom", "GB"),
                ("France", "FR"),
                ("Italy", "IT"),
                ("Spain", "ES"),
                ("Ukraine", "UA"),
                ("Poland", "PL"),
                ("Romania", "RO"),
                ("Netherlands", "NL"),
                ("Belgium", "BE"),
                ("Greece", "GR"),
                ("Portugal", "PT"),
                ("Czechia", "CZ"),
                ("Hungary", "HU"),
                ("Sweden", "SE"),
                ("Austria", "AT"),
                ("Switzerland", "CH"),
                ("Bulgaria", "BG"),
                ("Denmark", "DK"),
                ("Finland", "FI"),
                ("Slovakia", "SK"),
                ("Norway", "NO"),
                ("Ireland", "IE"),
                ("Croatia", "HR"),
                ("Bosnia and Herzegovina", "BA"),
                ("Lithuania", "LT"),
                ("Slovenia", "SI"),
                ("Latvia", "LV"),
                ("Estonia", "EE"),
                ("North Macedonia", "MK"),
                ("Luxembourg", "LU"),
                ("Montenegro", "ME"),
                ("Malta", "MT"),
                ("Iceland", "IS"),
                ("Andorra", "AD"),
                ("Monaco", "MC"),
                ("Liechtenstein", "LI"),
                ("San Marino", "SM"),
                ("Vatican City", "VA"),
                ("Uzbekistan", "UZ"),
                ("Turkmenistan", "TM"),
                ("Tajikistan", "TJ"),
                ("Kyrgyzstan", "KG"),
                ("Ethiopia", "ET"),
                ("Tanzania", "TZ"),
                ("Kenya", "KE"),
                ("Uganda", "UG"),
                ("Angola", "AO"),
                ("Mozambique", "MZ"),
                ("Ghana", "GH"),
                ("Madagascar", "MG"),
                ("Cameroon", "CM"),
                ("Ivory Coast", "CI"),
                ("Niger", "NE"),
                ("Burkina Faso", "BF"),
                ("Mali", "ML"),
                ("Malawi", "MW"),
                ("Zambia", "ZM"),
                ("Senegal", "SN"),
                ("Chad", "TD"),
                ("Somalia", "SO"),
                ("Zimbabwe", "ZW"),
                ("Guinea", "GN"),
                ("Rwanda", "RW"),
                ("Benin", "BJ"),
                ("Burundi", "BI"),
                ("South Sudan", "SS"),
                ("Togo", "TG"),
                ("Sierra Leone", "SL"),
                ("Congo-Brazzaville", "CG"),
                ("Liberia", "LR"),
                ("Central African Republic", "CF"),
                ("Mauritania", "MR"),
                ("Eritrea", "ER"),
                ("Namibia", "NA"),
                ("Gambia", "GM"),
                ("Botswana", "BW"),
                ("Gabon", "GA"),
                ("Lesotho", "LS"),
                ("Guinea-Bissau", "GW"),
                ("Equatorial Guinea", "GQ"),
                ("Mauritius", "MU"),
                ("Eswatini", "SZ"),
                ("Djibouti", "DJ"),
                ("Comoros", "KM"),
                ("Cabo Verde", "CV"),
                ("Sao Tome and Principe", "ST"),
                ("Seychelles", "SC"),
            ]
            if country_subunits_by_iso_code(c[1]) is not None
        },
    },
    {
        "type": "continenten",
        "data": {
            "Noord-Amerika": ["US", "Canada"],
            "Latijns-Amerika": [
                "Brazil",
                "Mexico",
                "Colombia",
                "Argentina",
                "Peru",
                "Venezuela",
                "Chile",
                "Ecuador",
                "Guatemala",
                "Bolivia",
                "Haiti",
                "Cuba",
                "Dominican Republic",
                "Honduras",
                "Paraguay",
                "El Salvador",
                "Nicaragua",
                "Costa Rica",
                "Panama",
                "Uruguay",
                "Jamaica",
                "Trinidad and Tobago",
                "Guyana",
                "Suriname",
                "Belize",
                "Bahamas",
                "Barbados",
                "Saint Lucia",
                "Grenada",
                "Saint Vincent and the Grenadines",
                "Antigua and Barbuda",
                "Dominica",
                "Saint Kitts and Nevis",
            ],
            "Europa": [
                "Germany",
                "United Kingdom",
                "France",
                "Italy",
                "Spain",
                "Ukraine",
                "Poland",
                "Romania",
                "Netherlands",
                "Belgium",
                "Greece",
                "Portugal",
                "Czechia",
                "Hungary",
                "Sweden",
                "Austria",
                "Switzerland",
                "Bulgaria",
                "Denmark",
                "Finland",
                "Slovakia",
                "Norway",
                "Ireland",
                "Croatia",
                "Bosnia and Herzegovina",
                "Lithuania",
                "Slovenia",
                "Latvia",
                "Estonia",
                "North Macedonia",
                "Luxembourg",
                "Montenegro",
                "Malta",
                "Iceland",
                "Andorra",
                "Monaco",
                "Liechtenstein",
                "San Marino",
                "Vatican City",
            ],
            "Rusland en Centraal-Azië": [
                "Russia",
                "Kazakhstan",
                "Uzbekistan",
                "Turkmenistan",
                "Tajikistan",
                "Kyrgyzstan",
            ],
            "Oost-Azië": [
                "China",
            ],
            "Zuid-Azië": [
                "India",
                "Pakistan",
                "Bangladesh",
                "Nepal",
                "Sri Lanka",
                "Bhutan",
                "Maldives",
            ],
            "Zuidoost-Azië": [
                "Indonesia",
                "Philippines",
                "Vietnam",
                "Thailand",
                "Myanmar",
                "Malaysia",
                "Cambodia",
                "Laos",
                "Singapore",
                "Timor-Leste",
                "Brunei",
            ],
            "Midden-Oosten": [
                "Turkey",
                "Iran",
                "Iraq",
                "Saudi Arabia",
                "Yemen",
                "Syria",
                "Jordan",
                "United Arab Emirates",
                "Israel",
                "Lebanon",
                "Oman",
                "Palestine",
                "Kuwait",
                "Qatar",
                "Bahrain",
                "Cyprus",
            ],
            "Noord-Afrika": [
                "Egypt",
                "Algeria",
                "Sudan",
                "Morocco",
                "Tunisia",
                "Libya",
            ],
            "Subsaharisch-Afrika": [
                "Nigeria",
                "Ethiopia",
                "Congo (Democratic Republic)",
                "Tanzania",
                "South Africa",
                "Kenya",
                "Uganda",
                "Angola",
                "Mozambique",
                "Ghana",
                "Madagascar",
                "Cameroon",
                "Ivory Coast",
                "Niger",
                "Burkina Faso",
                "Mali",
                "Malawi",
                "Zambia",
                "Senegal",
                "Chad",
                "Somalia",
                "Zimbabwe",
                "Guinea",
                "Rwanda",
                "Benin",
                "Burundi",
                "South Sudan",
                "Togo",
                "Sierra Leone",
                "Congo-Brazzaville",
                "Liberia",
                "Central African Republic",
                "Mauritania",
                "Eritrea",
                "Namibia",
                "Gambia",
                "Botswana",
                "Gabon",
                "Lesotho",
                "Guinea-Bissau",
                "Equatorial Guinea",
                "Mauritius",
                "Eswatini",
                "Djibouti",
                "Comoros",
                "Cabo Verde",
                "Sao Tome and Principe",
                "Seychelles",
            ],
            "Australië en Oceanië": [
                "Australia",
            ],
        },
    },
    {
        "type": "wereldblokken",
        "data": {
            "Noord-Amerika": ["US", "Canada"],
            "Latijns-Amerika": [
                "Brazil",
                "Mexico",
                "Colombia",
                "Argentina",
                "Peru",
                "Venezuela",
                "Chile",
                "Ecuador",
                "Guatemala",
                "Bolivia",
                "Haiti",
                "Cuba",
                "Dominican Republic",
                "Honduras",
                "Paraguay",
                "El Salvador",
                "Nicaragua",
                "Costa Rica",
                "Panama",
                "Uruguay",
                "Jamaica",
                "Trinidad and Tobago",
                "Guyana",
                "Suriname",
                "Belize",
                "Bahamas",
                "Barbados",
                "Saint Lucia",
                "Grenada",
                "Saint Vincent and the Grenadines",
                "Antigua and Barbuda",
                "Dominica",
                "Saint Kitts and Nevis",
            ],
            "Europa": [
                "Germany",
                "United Kingdom",
                "France",
                "Italy",
                "Spain",
                "Ukraine",
                "Poland",
                "Romania",
                "Netherlands",
                "Belgium",
                "Greece",
                "Portugal",
                "Czechia",
                "Hungary",
                "Sweden",
                "Austria",
                "Switzerland",
                "Bulgaria",
                "Denmark",
                "Finland",
                "Slovakia",
                "Norway",
                "Ireland",
                "Croatia",
                "Bosnia and Herzegovina",
                "Lithuania",
                "Slovenia",
                "Latvia",
                "Estonia",
                "North Macedonia",
                "Luxembourg",
                "Montenegro",
                "Malta",
                "Iceland",
                "Andorra",
                "Monaco",
                "Liechtenstein",
                "San Marino",
                "Vatican City",
            ],
            "Rusland en Centraal-Azië": [
                "Russia",
                "Kazakhstan",
                "Uzbekistan",
                "Turkmenistan",
                "Tajikistan",
                "Kyrgyzstan",
            ],
            "Oost-Azië": [
                "China",
            ],
            "Zuid-Azië": [
                "India",
                "Pakistan",
                "Bangladesh",
                "Nepal",
                "Sri Lanka",
                "Bhutan",
                "Maldives",
            ],
            "Zuidoost-Azië": [
                "Indonesia",
                "Philippines",
                "Vietnam",
                "Thailand",
                "Myanmar",
                "Malaysia",
                "Cambodia",
                "Laos",
                "Singapore",
                "Timor-Leste",
                "Brunei",
            ],
            "Midden-Oosten": [
                "Turkey",
                "Iran",
                "Iraq",
                "Saudi Arabia",
                "Yemen",
                "Syria",
                "Jordan",
                "United Arab Emirates",
                "Israel",
                "Lebanon",
                "Oman",
                "Palestine",
                "Kuwait",
                "Qatar",
                "Bahrain",
                "Cyprus",
            ],
            "Noord-Afrika": [
                "Egypt",
                "Algeria",
                "Sudan",
                "Morocco",
                "Tunisia",
                "Libya",
            ],
            "Subsaharisch-Afrika": [
                "Nigeria",
                "Ethiopia",
                "Congo (Democratic Republic)",
                "Tanzania",
                "South Africa",
                "Kenya",
                "Uganda",
                "Angola",
                "Mozambique",
                "Ghana",
                "Madagascar",
                "Cameroon",
                "Ivory Coast",
                "Niger",
                "Burkina Faso",
                "Mali",
                "Malawi",
                "Zambia",
                "Senegal",
                "Chad",
                "Somalia",
                "Zimbabwe",
                "Guinea",
                "Rwanda",
                "Benin",
                "Burundi",
                "South Sudan",
                "Togo",
                "Sierra Leone",
                "Congo-Brazzaville",
                "Liberia",
                "Central African Republic",
                "Mauritania",
                "Eritrea",
                "Namibia",
                "Gambia",
                "Botswana",
                "Gabon",
                "Lesotho",
                "Guinea-Bissau",
                "Equatorial Guinea",
                "Mauritius",
                "Eswatini",
                "Djibouti",
                "Comoros",
                "Cabo Verde",
                "Sao Tome and Principe",
                "Seychelles",
            ],
            "Australië en Oceanië": [
                "Australia",
            ],
        },
    },
]
